import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const baseURL = process.env.STILL_BASE_URL ?? 'http://localhost:3200';
const browser = await chromium.launch({ headless: true });
const testUser = { id: 'visual-user', name: 'Still Visual QA', email: 'visual@example.com', timezone: 'UTC', weeklyTarget: 5 };
const testPost = { id: 'visual-session', userId: testUser.id, authorName: testUser.name, completedAt: new Date().toISOString(), plannedSeconds: 600, elapsedSeconds: 600, sessionName: 'Quiet sitting', kudos: 4, comments: 1, viewerHasKudosed: false };
try {
  const page = await browser.newPage({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 1 });
  await page.route('**/api/auth/me', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ user: testUser }) }));
  await page.route('**/api/sessions', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ sessions: [], practiceDates: [] }) }));
  await page.route('**/api/feed*', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ feed: [testPost] }) }));
  await page.addInitScript(({ post }) => { const original = window.fetch; window.fetch = (input, init) => { const url = typeof input === 'string' ? input : input.url; if (url.includes('/api/feed')) return Promise.resolve(new Response(JSON.stringify({ feed: [post] }), { status: 200, headers: { 'Content-Type': 'application/json' } })); return original(input, init); }; }, { post: testPost });
  await page.addInitScript(() => { localStorage.setItem('still:reflection-session:visual-user', 'visual-session'); localStorage.setItem('still:reflection:visual-user', JSON.stringify({ beforeMood: 2, duringMood: 3, afterMood: 4, notes: 'A quiet note.' })); });
  await page.route('**/api/sessions/visual-session/comments', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ comments: [{ id: 'visual-comment', userId: 'friend', name: 'A Friend', body: 'A quiet return.', createdAt: new Date().toISOString() }] }) }));
  await page.goto(baseURL, { waitUntil: 'networkidle' });
  await page.addStyleTag({ content: ':root{--qa-safe-top:59px;--qa-safe-bottom:34px}.topbar{padding-top:59px}.bottom-nav{height:106px;padding-bottom:34px}' });
  const cta = page.locator('.practice-view button.primary-button');
  const nav = page.locator('.bottom-nav');
  const ctaBox = await cta.first().boundingBox();
  const navBox = await nav.boundingBox();
  assert.ok(ctaBox && navBox && ctaBox.y + ctaBox.height <= navBox.y - 8, 'practice CTA must clear the bottom nav');
  await page.getByText('How did it feel?').waitFor();
  assert.equal(await page.getByLabel('Notes').count(), 1, 'reflection must have one Notes field');
  assert.equal(await page.locator('.mood-field').count(), 3, 'reflection must have three mood ratings');
  await page.screenshot({ path: '/private/tmp/still-visual-notes.png', fullPage: true });
  await page.getByRole('button', { name: /skip for now/i }).click();
  await page.evaluate(() => { localStorage.removeItem('still:reflection-session:visual-user'); localStorage.removeItem('still:reflection:visual-user'); });
  await page.locator('.modal-backdrop').evaluate((node) => node.remove()).catch(() => undefined);
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Circle' }).click();
  await page.getByRole('heading', { name: 'People who sit.' }).waitFor();
  const authorCount = await page.locator('article.post').filter({ hasText: 'Still Visual QA' }).count();
  assert.equal(authorCount, 1, 'feed must be scoped to the deterministic test author');
  const post = page.locator('article.post').filter({ hasText: 'Still Visual QA' });
  await post.getByRole('button', { name: /comments/ }).click();
  await page.getByText('A quiet return.').waitFor();
  assert.equal(await page.locator('.comment-form input[aria-label="Comment"]').count(), 1);
  await page.screenshot({ path: '/private/tmp/still-visual-circle-expanded.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 667 });
  await page.screenshot({ path: '/private/tmp/still-visual-narrow-circle.png', fullPage: true });
  const desktop = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  await desktop.route('**/api/auth/me', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ user: testUser }) }));
  await desktop.route('**/api/sessions', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ sessions: [], practiceDates: [] }) }));
  await desktop.goto(baseURL, { waitUntil: 'networkidle' });
  await desktop.screenshot({ path: '/private/tmp/still-visual-desktop.png', fullPage: true });
  await desktop.close();
  console.log(JSON.stringify({ ok: true, screenshots: ['/private/tmp/still-visual-circle-expanded.png', '/private/tmp/still-visual-narrow-circle.png', '/private/tmp/still-visual-desktop.png'] }));
} finally { await browser.close(); }
