import { act, render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react'
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import PracticeTimer from '@/components/PracticeTimer'
const user={id:'early-user',name:'Ada'}
const key='still:practice:early-user'
function seed(earlyCompletion?: {elapsedSeconds:number;completedAt:string;notes:string}) {
  localStorage.setItem(key,JSON.stringify({local:true,sessionId:'early-session',startedAt:new Date(Date.now()-40000).toISOString(),plannedSeconds:600,deadlineMs:Date.now()+570000,paused:true,pausedRemainingSeconds:570,...(earlyCompletion?{earlyCompletion,completionPending:true}:{})}))
}
beforeEach(()=>{localStorage.clear();vi.spyOn(navigator,'onLine','get').mockReturnValue(false);vi.stubGlobal('fetch',vi.fn());seed()})
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals()})
it('asks before ending and resumes to the unchanged paused timer without saving a reason',async()=>{
  render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));expect(screen.getByRole('dialog')).toHaveAccessibleName('Why are you ending early?');fireEvent.change(screen.getByRole('textbox'),{target:{value:'Not actually ending'}});fireEvent.click(screen.getByRole('button',{name:'Resume sit'}));expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByText('paused')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Resume'})).toBeInTheDocument();expect(JSON.parse(localStorage.getItem(key)!).pausedRemainingSeconds).toBe(570);expect(localStorage.getItem('still:outbox:early-user')).toBeNull();expect(fetch).not.toHaveBeenCalled()
})
it('records only practiced time, carries an optional private reason into reflection, then resets after saving',async()=>{
  render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'  Phone rang  '}});fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByText('How did it feel?');expect(screen.getByRole('textbox')).toHaveValue('Ended early: Phone rang');const job=JSON.parse(localStorage.getItem('still:outbox:early-user')!)[0];expect(job.practice).toMatchObject({elapsedSeconds:30,endedEarly:true,plannedSeconds:600});expect(job.reflection.afterNote).toBe('Ended early: Phone rang');expect(localStorage.getItem(key)).toBeNull();fireEvent.click(screen.getByRole('button',{name:/Save reflection/}));await screen.findByRole('button',{name:/Begin practice/});expect(screen.queryByRole('dialog')).toBeNull()
})
it('allows an empty reason and preserves existing reflection notes',async()=>{
  localStorage.setItem('still:reflection:early-user',JSON.stringify({notes:'Existing note'}));render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByText('How did it feel?');expect(screen.getByRole('textbox')).toHaveValue('Existing note')
})
it('rejects oversized combined notes and retains the paused sit and both drafts',async()=>{
  localStorage.setItem('still:reflection:early-user',JSON.stringify({notes:'x'.repeat(6500)}));render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Reason'}});fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('6,500');expect(screen.getByRole('textbox')).toHaveValue('Reason');expect(screen.getByRole('button',{name:'Resume sit'})).toBeEnabled();expect(localStorage.getItem(key)).not.toBeNull()
})
it('recovers a confirmed early ending using its original duration and reason',async()=>{
  seed({elapsedSeconds:30,completedAt:new Date().toISOString(),notes:'Ended early: Appointment'});render(<PracticeTimer user={user}/>);await screen.findByText('well done');expect(screen.queryByRole('dialog')).toBeNull();fireEvent.click(screen.getByRole('button',{name:/Record reflection/}));expect(screen.getByRole('textbox')).toHaveValue('Ended early: Appointment');expect(JSON.parse(localStorage.getItem('still:outbox:early-user')!)[0].practice.elapsedSeconds).toBe(30)
})
it('retries the same confirmed ending after an outbox failure without permitting an ambiguous resume',async()=>{
  render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Reason'}});
  const original=Storage.prototype.setItem;const fail=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,storageKey,value){if(storageKey.startsWith('still:outbox:'))throw new Error('quota');original.call(this,storageKey,value)})
  fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('quota');expect(screen.getByRole('button',{name:'Resume sit'})).toBeDisabled();const pending=JSON.parse(localStorage.getItem(key)!);expect(pending.earlyCompletion.notes).toBe('Ended early: Reason');fail.mockRestore();fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByText('How did it feel?');expect(JSON.parse(localStorage.getItem('still:outbox:early-user')!)[0].practice.completedAt).toBe(pending.earlyCompletion.completedAt)
})
it('keeps the reason form when recovery storage fails before confirmation',async()=>{
  render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw 'blocked'});fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('Could not save your session.');expect(screen.getByRole('button',{name:'Resume sit'})).toBeEnabled()
})
it('restores the confirmed reason while preserving moods from an older draft',async()=>{
  seed({elapsedSeconds:30,completedAt:new Date().toISOString(),notes:'Ended early: Appointment'});localStorage.setItem('still:reflection:early-user',JSON.stringify({beforeMood:3,notes:'Older draft'}));render(<PracticeTimer user={user}/>);await screen.findByText('well done');fireEvent.click(screen.getByRole('button',{name:/Record reflection/}));expect(screen.getByRole('textbox')).toHaveValue('Ended early: Appointment');expect(screen.getByRole('button',{name:'Before 3 of 5'})).toHaveClass('selected')
})
it('fits both dialogs to the visible keyboard viewport and removes listeners when closed',async()=>{
  const viewport=Object.assign(new EventTarget(),{height:360,offsetTop:12});const remove=vi.spyOn(viewport,'removeEventListener');Object.defineProperty(window,'visualViewport',{configurable:true,value:viewport})
  render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));await waitFor(()=>expect((document.querySelector('.modal-backdrop') as HTMLElement).style.height).toBe('360px'));expect((document.querySelector('.modal-backdrop') as HTMLElement).style.top).toBe('12px');viewport.height=300;await act(async()=>{viewport.dispatchEvent(new Event('resize'))});await waitFor(()=>expect((document.querySelector('.modal-backdrop') as HTMLElement).style.height).toBe('300px'));await act(async()=>{viewport.dispatchEvent(new Event('scroll'))});fireEvent(window,new Event('resize'));fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByText('How did it feel?');expect((document.querySelector('.modal-backdrop') as HTMLElement).style.height).toBe('300px');fireEvent.click(screen.getByRole('button',{name:/Save reflection/}));await screen.findByRole('button',{name:/Begin practice/});expect(remove).toHaveBeenCalledWith('resize',expect.any(Function));expect(remove).toHaveBeenCalledWith('scroll',expect.any(Function));Object.defineProperty(window,'visualViewport',{configurable:true,value:undefined})
})
it('adds the optional reason as a paragraph without discarding existing notes',async()=>{
  localStorage.setItem('still:reflection:early-user',JSON.stringify({notes:'Existing note'}));render(<PracticeTimer user={user}/>);fireEvent.click(await screen.findByRole('button',{name:/End session early/}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Doorbell'}});fireEvent.click(screen.getByRole('button',{name:'End session'}));await screen.findByText('How did it feel?');expect(screen.getByRole('textbox')).toHaveValue('Ended early: Doorbell\n\nExisting note')
})
