import { describe, expect, it, vi } from 'vitest'

describe('http helpers', () => {
  it('rejects missing and unknown sessions, then returns the authenticated user', async () => {
    vi.resetModules()
    const cookieStore = { get: vi.fn().mockReturnValue(undefined) }
    const query = vi.fn().mockResolvedValue([])
    vi.doMock('next/headers', () => ({ cookies: () => cookieStore, headers: () => new Headers() }))
    vi.doMock('../../../src/lib/db', () => ({ sql: () => query }))
    const http = await import('../../../src/lib/http')
    await expect(http.requireUser()).rejects.toMatchObject({ status: 401 })
    cookieStore.get.mockReturnValue({ value: 'session-token' })
    await expect(http.requireUser()).rejects.toMatchObject({ status: 401 })
    query.mockResolvedValueOnce([{ id: 'u1', email: 'a@example.test', name: 'A', timezone: 'UTC', weekly_target: 7, weekly_minutes_target: null, avatarKey: null }])
    await expect(http.requireUser()).resolves.toMatchObject({ id: 'u1', weekly_target: 7 })
    expect(query.mock.calls.at(-1)?.[0]).toContain('sessions s JOIN users u')
  })

  it('guards cross-origin writes and emits uncached JSON', async () => {
    vi.resetModules()
    const headerValues = new Headers({ origin: 'https://evil.test', host: 'still.test' })
    vi.doMock('next/headers', () => ({ cookies: () => ({ get: () => undefined }), headers: () => headerValues }))
    vi.doMock('../../../src/lib/db', () => ({ sql: () => vi.fn() }))
    const http = await import('../../../src/lib/http')
    await expect(http.originGuard()).rejects.toMatchObject({ status: 403 })
    headerValues.delete('origin')
    await expect(http.originGuard()).resolves.toBeUndefined()
    const response = http.json({ ok: true }, 201)
    expect(response.status).toBe(201)
    expect(response.headers.get('cache-control')).toBe('no-store')
    await expect(response.json()).resolves.toEqual({ ok: true })
    headerValues.set('origin', 'https://still.test')
    headerValues.set('host', 'still.test')
    await expect(http.originGuard()).resolves.toBeUndefined()
    headerValues.set('origin', 'malformed')
    await expect(http.originGuard()).rejects.toMatchObject({ status: 403 })
  })

  it('rejects malformed origins and missing hosts', async () => {
    vi.resetModules()
    const values = new Headers({ origin: 'not-a-url' })
    vi.doMock('next/headers', () => ({ cookies: () => ({ get: () => undefined }), headers: () => values }))
    vi.doMock('../../../src/lib/db', () => ({ sql: () => vi.fn() }))
    const http = await import('../../../src/lib/http')
    await expect(http.originGuard()).rejects.toMatchObject({ status: 403 })
    vi.resetModules()
    vi.doUnmock('next/headers')
    vi.doMock('next/headers', () => ({ cookies: () => ({ get: () => undefined }), headers: () => new Headers() }))
    vi.doMock('../../../src/lib/db', () => ({ sql: () => vi.fn() }))
    const noOrigin = await import('../../../src/lib/http')
    await expect(noOrigin.originGuard()).resolves.toBeUndefined()
    vi.resetModules()
    vi.doUnmock('next/headers')
    const missingHost = new Headers({ origin: 'https://example.test' })
    vi.doMock('next/headers', () => ({ cookies: () => ({ get: () => undefined }), headers: () => missingHost }))
    vi.doMock('../../../src/lib/db', () => ({ sql: () => vi.fn() }))
    const noHost = await import('../../../src/lib/http')
    await expect(noHost.originGuard()).rejects.toMatchObject({ status: 403 })
  })
})
